# Generated by Django 4.2.7 on 2025-08-06 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armada',
            fields=[
                ('id_armada', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_polisi', models.CharField(max_length=15)),
                ('jenis_armada', models.CharField(max_length=50)),
                ('kapasitas_muatan', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('warna_armada', models.CharField(max_length=20)),
                ('id_stnk', models.CharField(max_length=30)),
                ('tahun_pembuatan', models.DateTimeField()),
                ('id_bpkb', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id_audit', models.AutoField(primary_key=True, serialize=False)),
                ('nama_tabel', models.CharField(max_length=50)),
                ('id_record', models.IntegerField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('changed_by', models.CharField(max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id_bank', models.AutoField(primary_key=True, serialize=False)),
                ('nama_bank', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id_delivery_order', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_kirim', models.DateTimeField()),
                ('gps_log', models.JSONField()),
                ('status', models.CharField(max_length=20)),
                ('id_armada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.armada')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id_driver', models.AutoField(primary_key=True, serialize=False)),
                ('no_hp', models.CharField(max_length=15)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('wkt_daftar', models.DateTimeField(auto_now_add=True)),
                ('alamat', models.TextField()),
                ('ttl', models.DateField()),
                ('nik', models.CharField(max_length=16)),
                ('no_sim', models.CharField(max_length=20)),
                ('jenis_sim', models.CharField(max_length=10)),
                ('no_bpjs', models.CharField(max_length=20)),
                ('nama_kontak_darurat', models.CharField(max_length=100)),
                ('nomor_kontak_darurat', models.CharField(max_length=15)),
                ('hubungan_kontak_darurat', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id_pelanggan', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('ID_Produk', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_Produk', models.CharField(max_length=100)),
                ('Deskripsi', models.TextField()),
                ('Kategori', models.CharField(max_length=50)),
                ('Satuan', models.CharField(max_length=20)),
                ('Barcode_Produk', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id_sales_order', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_order', models.DateTimeField()),
                ('total_harga_order', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alamat_pengiriman', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle')], max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='RiwayatPerjalanan',
            fields=[
                ('id_perjalanan', models.AutoField(primary_key=True, serialize=False)),
                ('rute', models.TextField()),
                ('tanggal', models.DateTimeField()),
                ('jarak_tempuh_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('durasi_perjalanan', models.IntegerField()),
                ('id_delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.deliveryorder')),
            ],
        ),
        migrations.CreateModel(
            name='RekeningDriver',
            fields=[
                ('id_rekening', models.AutoField(primary_key=True, serialize=False)),
                ('nomor_rekening', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('id_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.bank')),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='RatingDriver',
            fields=[
                ('id_rating', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('ulasan', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='PembayaranFee',
            fields=[
                ('id_pembayaran', models.AutoField(primary_key=True, serialize=False)),
                ('metode_pembayaran', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer'), ('ewallet', 'E-Wallet')], max_length=20)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tanggal', models.DateTimeField()),
                ('id_delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.deliveryorder')),
                ('id_rekening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.rekeningdriver')),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id_notifikasi', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_notifikasi', models.CharField(max_length=50)),
                ('isi_pesan', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='LogPanggilan',
            fields=[
                ('id_panggilan', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rekaman_panggilan', models.CharField(max_length=255)),
                ('durasi_panggilan', models.IntegerField()),
                ('id_penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.pelanggan')),
                ('id_pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_made', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='LogIstirahatDriver',
            fields=[
                ('id_rest_log', models.AutoField(primary_key=True, serialize=False)),
                ('start_rest_time', models.DateTimeField()),
                ('end_rest_time', models.DateTimeField()),
                ('durasi_istirahat', models.IntegerField()),
                ('lokasi', models.JSONField()),
                ('id_delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.deliveryorder')),
            ],
        ),
        migrations.CreateModel(
            name='LogChat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isi_pesan', models.TextField()),
                ('id_penerima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.pelanggan')),
                ('id_pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sent', to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='LogAttachmentChat',
            fields=[
                ('id_attach_chat', models.AutoField(primary_key=True, serialize=False)),
                ('tipe_file', models.CharField(max_length=20)),
                ('ukuran_file', models.IntegerField()),
                ('file', models.TextField()),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.logchat')),
            ],
        ),
        migrations.CreateModel(
            name='LaporanDarurat',
            fields=[
                ('id_laporan', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_insiden', models.CharField(max_length=50)),
                ('isi_laporan', models.TextField()),
                ('lokasi', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverAttachment',
            fields=[
                ('id_attachment', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('sim', 'SIM'), ('ktp', 'KTP'), ('bpjs', 'BPJS'), ('foto', 'Foto')], max_length=10)),
                ('file_dok', models.TextField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='id_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='id_sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.salesorder'),
        ),
        migrations.CreateModel(
            name='SalesorderProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('satuan', models.CharField(max_length=20)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.produk')),
                ('id_sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.salesorder')),
            ],
            options={
                'unique_together': {('id_sales_order', 'id_produk')},
            },
        ),
        migrations.CreateModel(
            name='DriverDeliveryorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_assign', models.DateTimeField()),
                ('status_tugas', models.CharField(max_length=20)),
                ('id_delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.deliveryorder')),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
            options={
                'unique_together': {('id_driver', 'id_delivery_order')},
            },
        ),
        migrations.CreateModel(
            name='DriverArmada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_mulai', models.DateTimeField()),
                ('tanggal_selesai', models.DateTimeField()),
                ('id_armada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.armada')),
                ('id_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
            ],
            options={
                'unique_together': {('id_driver', 'id_armada')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryorderSalesorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_produk_terkirim', models.IntegerField()),
                ('status_pengiriman', models.CharField(max_length=20)),
                ('tanggal_pengiriman', models.DateTimeField()),
                ('id_delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.deliveryorder')),
                ('id_produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.produk')),
                ('id_sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.salesorder')),
            ],
            options={
                'unique_together': {('id_delivery_order', 'id_sales_order', 'id_produk')},
            },
        ),
        migrations.CreateModel(
            name='ArmadaDeliveryorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pakai', models.DateTimeField()),
                ('kapasitas_digunakan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_armada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.armada')),
                ('id_delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.deliveryorder')),
            ],
            options={
                'unique_together': {('id_delivery_order', 'id_armada')},
            },
        ),
    ]
