# Generated by Django 4.2.7 on 2025-08-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='alasan_penolakan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='foto_ktp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='foto_profil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='foto_sertifikat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='foto_sim',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
