# Generated by Django 4.2.7 on 2025-08-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_alasan_penolakan_driver_foto_ktp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='foto_bpjs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
