# Generated by Django 4.2.7 on 2025-08-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_foto_bpjs'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='nama_bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='nomor_rekening',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
