# Generated by Django 4.2.7 on 2025-08-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_trainingmodule_trainingquiz_trainingcontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertrainingprogress',
            name='quiz_score',
        ),
        migrations.AddField(
            model_name='drivertrainingprogress',
            name='current_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drivertrainingprogress',
            name='quiz_answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='drivertrainingprogress',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='trainingquiz',
            name='points',
            field=models.IntegerField(default=20),
        ),
    ]
