# Generated by Django 4.2.7 on 2025-08-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_remove_drivertrainingprogress_quiz_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='no_sertifikat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='tanggal_kedaluarsa_bpjs',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='tanggal_kedaluarsa_sertifikat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='tanggal_kedaluarsa_sim',
            field=models.DateField(blank=True, null=True),
        ),
    ]
