# Generated by Django 4.2.7 on 2025-08-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_driver_no_sertifikat_driver_tanggal_kedaluarsa_bpjs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('training', 'Training'), ('pending', 'Pending Approval'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
