# Generated by Django 4.2.7 on 2025-08-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_alter_driver_status'),
    ]

    operations = [
    ]
