# Generated by Django 4.2.7 on 2025-08-22 01:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_auto_20250822_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingcontent',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainingquiz',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='trainingcontent',
            name='order',
        ),
        migrations.RemoveField(
            model_name='trainingquiz',
            name='order',
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='training_media/'),
        ),
        migrations.AddField(
            model_name='trainingcontent',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingquiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
