# Generated by Django 4.2.7 on 2025-08-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_alter_trainingcontent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingmodule',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='trainingmodule',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
