# Generated by Django 4.2.7 on 2025-08-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_alter_trainingmodule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armada',
            name='foto_bpkb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='armada',
            name='foto_stnk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
