# Generated by Django 4.2.7 on 2025-09-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_armada_foto_bpkb_armada_foto_stnk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverarmada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
