# Generated by Django 4.2.7 on 2025-09-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0014_alter_driverarmada_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='kota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
