\connect om;

CREATE TABLE IF NOT EXISTS "role" (
  "id_role" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_role" VARCHAR,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_role")
);

CREATE TABLE IF NOT EXISTS "produk" (
  "id_produk" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kode_produk" VARCHAR,
  "id_satuan" INTEGER,
  "id_mata_uang" INTEGER,
  "id_kategori" INTEGER,
  "id_tenant" INTEGER,
  "nama_produk" VARCHAR,
  "barcode_produk" VARCHAR,
  "strategi_penyimpanan" VARCHAR,
  "deskripsi" TEXT,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "harga" DECIMAL,
  PRIMARY KEY ("id_produk")
);

CREATE TABLE IF NOT EXISTS "po" (
  "id_po" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nomor_po" VARCHAR,
  "id_tenant" INTEGER,
  "tgl_po" DATE,
  "harga_total" DECIMAL,
  PRIMARY KEY ("id_po")
);

CREATE TABLE IF NOT EXISTS "order" (
  "id_order" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tgl_order" DATE,
  "id_jenis_order" INTEGER,
  "id_pembeli" INTEGER,
  "nomor_order" VARCHAR,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_order")
);

CREATE TABLE IF NOT EXISTS "gudang" (
  "id_gudang" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_gudang" VARCHAR,
  "jumlah" INTEGER,
  "alamat" TEXT,
  "id_statusgudang" INTEGER,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_gudang")
);

CREATE TABLE IF NOT EXISTS "lokasi_rak" (
  "id_lokasi" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_gudang" INTEGER,
  "nama_lokasi" VARCHAR,
  "barcode_lokasi" VARCHAR,
  "jumlah" INTEGER,
  "kapasitas_berat" INTEGER,
  "kapasitas_volume" INTEGER,
  "status_penuh" BOOLEAN,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_lokasi")
);

CREATE TABLE IF NOT EXISTS "stok" (
  "id_stok" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_lokasi" INTEGER,
  "jumlah" INTEGER,
  "tgl_masuk" DATE,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "id_produk" INTEGER,
  PRIMARY KEY ("id_stok")
);

CREATE TABLE IF NOT EXISTS "quality_control" (
  "id_qc" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_po" INTEGER,
  "id_user" INTEGER,
  "catatan" TEXT,
  "id_status_qc" INTEGER,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_qc")
);

CREATE TABLE IF NOT EXISTS "pengembalian" (
  "id_pengembalian" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_produk" INTEGER,
  "id_satuan" INTEGER,
  "id_po" INTEGER,
  "jumlah" VARCHAR,
  "alasan" TEXT,
  PRIMARY KEY ("id_pengembalian")
);

CREATE TABLE IF NOT EXISTS "stok_movement" (
  "id_sm" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "no_stockmovement" VARCHAR,
  "id_user" INTEGER,
  "id_detail_sm" INTEGER,
  "keterangan" VARCHAR,
  "tgl_sm" DATE,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_sm")
);

CREATE TABLE IF NOT EXISTS "attachment" (
  "id_attachment" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_file" VARCHAR,
  "path_file" TEXT,
  "id_jenis_file" INTEGER,
  "tgl_upload" TIMESTAMP,
  "delete_flag" BOOLEAN,
  "no_dokumen" INTEGER,
  "mulai_berlaku" DATE,
  "akhir_berlaku" DATE,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_attachment")
);

CREATE TABLE IF NOT EXISTS "detail_qc" (
  "id_detailqc" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nomor_detaiqc" INTEGER,
  "nama_barang" VARCHAR,
  "jumlah_sample" VARCHAR,
  "id_kriteria_produk" INTEGER,
  "id_detailpo" INTEGER,
  "id_satuan" INTEGER,
  "tgl_cek" TIMESTAMP,
  "id_lokasi" INTEGER,
  "id_qc" INTEGER,
  "hasil_qc" VARCHAR,
  "memenuhi" BOOLEAN,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_detailqc")
);

CREATE TABLE IF NOT EXISTS "detail_stockmovement" (
  "id_detail_sm" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "jumlah" INTEGER,
  "id_lokasi" INTEGER,
  "id_satuan" INTEGER,
  "id_produk" INTEGER,
  PRIMARY KEY ("id_detail_sm")
);

CREATE TABLE IF NOT EXISTS "detail_po" (
  "id_detailpo" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_satuan" INTEGER,
  "id_produk" INTEGER,
  "id_po" INTEGER,
  "jumlah" INTEGER,
  "harga" DECIMAL,
  PRIMARY KEY ("id_detailpo")
);

CREATE TABLE IF NOT EXISTS "kategori_produk" (
  "id_kategori" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_kategori" VARCHAR,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_kategori")
);

CREATE TABLE IF NOT EXISTS "satuan" (
  "id_satuan" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_satuan" VARCHAR,
  "simbol_satuan" VARCHAR,
  "id_jenis" INTEGER,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_satuan")
);

CREATE TABLE IF NOT EXISTS "jenis_satuan" (
  "id_jenis" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_jenis" VARCHAR,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_jenis")
);

CREATE TABLE IF NOT EXISTS "konversi" (
  "id_konversi" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_produk" INTEGER,
  "id_satuan" INTEGER,
  "id_satuan_konversi" INTEGER,
  "quantity" VARCHAR,
  "quantity_konversi" VARCHAR,
  PRIMARY KEY ("id_konversi")
);

CREATE TABLE IF NOT EXISTS "produk_gudang" (
  "id_produk_gudang" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_gudang" INTEGER,
  "id_satuan" INTEGER,
  "id_produk" INTEGER,
  "harga" DECIMAL,
  "id_mata_uang" INTEGER,
  "quantity_harga" VARCHAR,
  PRIMARY KEY ("id_produk_gudang")
);

CREATE TABLE IF NOT EXISTS "mata_uang" (
  "id_mata_uang" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kode_mata_uang" VARCHAR,
  "simbol_mata_uang" VARCHAR,
  "nama_mata_uang" VARCHAR,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_mata_uang")
);

CREATE TABLE IF NOT EXISTS "atribut" (
  "id_atribut" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_atribut" VARCHAR,
  PRIMARY KEY ("id_atribut")
);

CREATE TABLE IF NOT EXISTS "atribut_produk" (
  "id_atribut_produk" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_satuan" INTEGER,
  "id_atribut" INTEGER,
  "id_produk" INTEGER,
  "nilai" VARCHAR,
  PRIMARY KEY ("id_atribut_produk")
);

CREATE TABLE IF NOT EXISTS "status_qc" (
  "id_status_qc" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_status" VARCHAR,
  PRIMARY KEY ("id_status_qc")
);

CREATE TABLE IF NOT EXISTS "kriteria_produk" (
  "id_kriteria_produk" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_produk" INTEGER,
  "nama_kriteria" VARCHAR,
  "batas_min" VARCHAR,
  "batas_max" VARCHAR,
  "id_satuan" INTEGER,
  "memenuhi" BOOLEAN,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_kriteria_produk")
);

CREATE TABLE IF NOT EXISTS "tenant" (
  "id_tenant" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_tenant" VARCHAR,
  "alamat_tenant" TEXT,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_tenant")
);

CREATE TABLE IF NOT EXISTS "user_tenant" (
  "id_user_tenant" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_tenant" INTEGER,
  "id_user" INTEGER,
  PRIMARY KEY ("id_user_tenant")
);

CREATE TABLE IF NOT EXISTS "attachment_pengembalian" (
  "id_attachment" INTEGER,
  "id_pengembalian" INTEGER,
  "no_urut" INTEGER
);

CREATE TABLE IF NOT EXISTS "attachment_qc" (
  "id_detailqc" INTEGER,
  "id_attachment" INTEGER,
  "no_urut" INTEGER
);

CREATE TABLE IF NOT EXISTS "attachment_gudang" (
  "id_attachment" INTEGER,
  "id_gudang" INTEGER,
  "no_urut" INTEGER
);

CREATE TABLE IF NOT EXISTS "status_gudang" (
  "id_statusgudang" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_status" VARCHAR,
  PRIMARY KEY ("id_statusgudang")
);

CREATE TABLE IF NOT EXISTS "jenis_file" (
  "id_jenis_file" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "jenis_file" VARCHAR,
  "id_jenis_transaksi" INTEGER,
  "max_ukuran" INTEGER,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_jenis_file")
);

CREATE TABLE IF NOT EXISTS "jenis_transaksi" (
  "id_jenis_transaksi" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_transaksi" VARCHAR,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_jenis_transaksi")
);

CREATE TABLE IF NOT EXISTS "daftar_user" (
  "id_user" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_status" INTEGER,
  "id_kontakdarurat" INTEGER,
  "nama" VARCHAR,
  "email" VARCHAR,
  "no_hp" VARCHAR,
  "alamat" TEXT,
  "password" VARCHAR,
  "wkt_daftar" TIMESTAMP,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_user")
);

CREATE TABLE IF NOT EXISTS "attachment_driver" (
  "id_attachment" INTEGER,
  "id_user" INTEGER
);

CREATE TABLE IF NOT EXISTS "sales_order" (
  "id_sales_order" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "harga_total" DECIMAL,
  "alamat_jemput" TEXT,
  "alamat_pengiriman" TEXT,
  PRIMARY KEY ("id_sales_order")
);

CREATE TABLE IF NOT EXISTS "delivery_order" (
  "id_delivery_order" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_user" INTEGER NOT NULL,
  "id_armada" INTEGER NOT NULL,
  "no_delivery_order" VARCHAR,
  "gps_log" VARCHAR,
  "tanggal_kirim" TIMESTAMP,
  "tanggal_terima" TIMESTAMP,
  "status_deliver" VARCHAR,
  PRIMARY KEY ("id_delivery_order")
);

CREATE TABLE IF NOT EXISTS "notifikasi" (
  "id_notifikasi" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_user" INTEGER NOT NULL,
  "id_jenis_notifikasi" INTEGER NOT NULL,
  "isi_pesan" TEXT,
  "waktu_terima_notifikasi" TIMESTAMP,
  "status_notifikasi" BOOLEAN,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_notifikasi")
);

CREATE TABLE IF NOT EXISTS "laporan_darurat" (
  "id_laporan" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_user" INTEGER NOT NULL,
  "id_jenis_insiden" INTEGER NOT NULL,
  "isi_laporan" TEXT,
  "lokasi_pelaporan_darurat" VARCHAR,
  "longitude" DECIMAL,
  "latitude" DECIMAL,
  "waktu_laporan" TIMESTAMP,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_laporan")
);

CREATE TABLE IF NOT EXISTS "log_chat" (
  "id_chat" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_pengirim" INTEGER NOT NULL,
  "id_penerima" INTEGER NOT NULL,
  "waktu_kirim" TIMESTAMP,
  "isi_pesan" TEXT,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "id_order" INTEGER NOT NULL,
  PRIMARY KEY ("id_chat")
);

CREATE TABLE IF NOT EXISTS "log_panggilan" (
  "id_panggilan" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_pengirim" INTEGER NOT NULL,
  "id_penerima" INTEGER NOT NULL,
  "waktu_panggilan" TIMESTAMP,
  "rekaman_panggilan" VARCHAR,
  "durasi_panggilan" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_panggilan")
);

CREATE TABLE IF NOT EXISTS "pembayaran_fee" (
  "id_fee" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_metode_pembayaran" INTEGER NOT NULL,
  "id_delivery_order" INTEGER NOT NULL,
  "id_rekening" INTEGER NOT NULL,
  "jumlah" DECIMAL,
  "tanggal" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  PRIMARY KEY ("id_fee")
);

CREATE TABLE IF NOT EXISTS "rekening_driver" (
  "id_rekening" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_user" INTEGER NOT NULL,
  "id_bank" INTEGER NOT NULL,
  "nomor_rekening" VARCHAR,
  "status_aktif" BOOLEAN,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_rekening")
);

CREATE TABLE IF NOT EXISTS "bank" (
  "id_bank" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_bank" VARCHAR,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_bank")
);

CREATE TABLE IF NOT EXISTS "rating" (
  "id_rating" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_delivery_order" INTEGER NOT NULL,
  "rating" INTEGER,
  "ulasan" TEXT,
  "waktu_rating" TIMESTAMP,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_rating")
);

CREATE TABLE IF NOT EXISTS "log_aktifitas_driver" (
  "id_aktifitas" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_gps_driver" INTEGER NOT NULL,
  "aktifitas_bergerak" BOOLEAN,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_aktifitas")
);

CREATE TABLE IF NOT EXISTS "driver_armada" (
  "id_user" INTEGER,
  "id_armada" INTEGER
);

CREATE TABLE IF NOT EXISTS "deliveryorder_salesorder" (
  "id_delivery_order" INTEGER,
  "id_sales_order" INTEGER
);

CREATE TABLE IF NOT EXISTS "chat_attachment" (
  "id_attachment" INTEGER,
  "id_chat" INTEGER
);

CREATE TABLE IF NOT EXISTS "status_driver" (
  "id_status" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "status_driver" VARCHAR,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_status")
);

CREATE TABLE IF NOT EXISTS "kontak_darurat" (
  "id_kontakdarurat" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nomor_kontak" INTEGER,
  "nama_kontak_darurat" VARCHAR,
  "hubungan" VARCHAR,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_kontakdarurat")
);

CREATE TABLE IF NOT EXISTS "tempat_istirahat_driver" (
  "id_tempat_istirahat" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_tempat" VARCHAR,
  "alamat" VARCHAR,
  "longitude" DECIMAL,
  "latitude" DECIMAL,
  "jam_buka" VARCHAR,
  "jam_tutup" VARCHAR,
  "hari_buka" VARCHAR,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_tempat_istirahat")
);

CREATE TABLE IF NOT EXISTS "jenis_notifikasi" (
  "id_jenis_notifikasi" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "jenis_notifikasi" VARCHAR,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_jenis_notifikasi")
);

CREATE TABLE IF NOT EXISTS "jenis_insiden" (
  "id_jenis_insiden" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "jenis_insiden" VARCHAR,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_jenis_insiden")
);

CREATE TABLE IF NOT EXISTS "metode_pembayaran" (
  "id_metode_pembayaran" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "jenis_metode" VARCHAR,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_metode_pembayaran")
);

CREATE TABLE IF NOT EXISTS "detail_deliveryorder" (
  "id_detail_DeliveryOrder" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_delivery_order" INTEGER NOT NULL,
  "quantity_kirim" INTEGER,
  "id_produk" INTEGER,
  PRIMARY KEY ("id_detail_DeliveryOrder")
);

CREATE TABLE IF NOT EXISTS "detail_salesorder" (
  "id_detail_SalesOrder" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_sales_order" INTEGER NOT NULL,
  "id_satuan" INTEGER NOT NULL,
  "id_produk" INTEGER NOT NULL,
  "jumlah" VARCHAR,
  "harga" DECIMAL,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_detail_SalesOrder")
);

CREATE TABLE IF NOT EXISTS "perangkat_gps_driver" (
  "id_gps_driver" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_user" INTEGER NOT NULL,
  "latitude" DECIMAL,
  "longtitude" DECIMAL,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_gps_driver")
);

CREATE TABLE IF NOT EXISTS "jenis_order" (
  "id_jenis_order" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nama_order" VARCHAR,
  PRIMARY KEY ("id_jenis_order")
);

CREATE TABLE IF NOT EXISTS "user_role" (
  "id_role" INTEGER NOT NULL,
  "id_user" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "armada_tms" (
  "id_armada" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_tenant" INTEGER NOT NULL,
  "no_mesin" VARCHAR(20) UNIQUE NOT NULL,
  "no_rangka" VARCHAR(20) UNIQUE NOT NULL,
  "no_polisi" VARCHAR(20) UNIQUE NOT NULL,
  "no_lambung" VARCHAR(255),
  "kapasitas_muatan" DECIMAL NOT NULL,
  "id_satuan" INTEGER NOT NULL,
  "id_jenis_armada" INTEGER NOT NULL,
  "id_status_armada" INTEGER NOT NULL,
  "merk_armada" VARCHAR(20) NOT NULL,
  "tahun_pembuatan" SMALLINT,
  "warna_armada" VARCHAR(50),
  PRIMARY KEY ("id_armada")
);

CREATE TABLE IF NOT EXISTS "perangkat" (
  "id_perangkat" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "merk" VARCHAR(100) NOT NULL,
  "model" VARCHAR(100),
  "tahun_produksi" INTEGER,
  "no_seri" VARCHAR(255) UNIQUE NOT NULL,
  "token" VARCHAR(255),
  PRIMARY KEY ("id_perangkat")
);

CREATE TABLE IF NOT EXISTS "rute" (
  "id_rute" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_geofence" INTEGER,
  "kode_rute" VARCHAR(50) NOT NULL,
  "asal" VARCHAR(255) NOT NULL,
  "tujuan" VARCHAR(255) NOT NULL,
  "jarak_km" DECIMAL(6,2) NOT NULL,
  "estimasi_waktu" INTEGER NOT NULL,
  "biaya_perjalanan" DECIMAL(15,2) NOT NULL,
  "jenis_kendaraan" VARCHAR(100) NOT NULL,
  "tanggal_update" TIMESTAMP NOT NULL,
  PRIMARY KEY ("id_rute")
);

CREATE TABLE IF NOT EXISTS "armada_perangkat" (
  "id_armada" INTEGER NOT NULL,
  "id_perangkat" INTEGER NOT NULL,
  "tanggal_pemasangan" TIMESTAMP NOT NULL,
  "tanggal_pembongkaran" TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "log_perangkat" (
  "id_log_perangkat" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_perangkat" INTEGER NOT NULL,
  "timestamp" TIMESTAMP NOT NULL,
  "latitude" DECIMAL(10,7) NOT NULL,
  "longitude" DECIMAL(10,7) NOT NULL,
  "kecepatan" DECIMAL(5,2),
  "arah" DECIMAL,
  "jarak" DECIMAL(10,2),
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_log_perangkat")
);

CREATE TABLE IF NOT EXISTS "pengingat_pemeliharaan_armada" (
  "id_pengingat_pemeliharaan" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_log_service" INTEGER,
  "id_armada" INTEGER NOT NULL,
  "jadwal_pemeliharaan" DATE NOT NULL,
  "biaya_perawatan" DECIMAL(15,2),
  "status_perawatan" VARCHAR(50),
  "prioritas" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_pengingat_pemeliharaan")
);

CREATE TABLE IF NOT EXISTS "laporan_pengemudi" (
  "id_laporan_pengemudi" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_user" INTEGER NOT NULL,
  "id_log_perjalanan_armada" INTEGER NOT NULL,
  "skor_kecepatan" DECIMAL(5,2),
  "skor_pengereman" DECIMAL(5,2),
  "skor_efisiensi_bahan_bakar" DECIMAL(5,2),
  "skor_kepatuhan_rute" DECIMAL(5,2),
  "total_skor" DECIMAL(5,2),
  "tanggal_penilaian" TIMESTAMP NOT NULL,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_laporan_pengemudi")
);

CREATE TABLE IF NOT EXISTS "attachment_perangkat" (
  "id_attachment" INTEGER NOT NULL,
  "id_perangkat" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "attachment_armada" (
  "id_attachment" INTEGER NOT NULL,
  "id_armada" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "alert_geofence" (
  "id_alert_geofence" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "id_geofence" INTEGER,
  "id_user" INTEGER,
  "jenis_kejadian" VARCHAR(255),
  "koordinat_kejadian" POINT,
  "kecepatan_saat_kejadian" NUMERIC,
  "tindakan_diambil" TEXT,
  "waktu_kejadian" TIMESTAMP,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_alert_geofence")
);

CREATE TABLE IF NOT EXISTS "geofence" (
  "id_geofence" INTEGER UNIQUE NOT NULL,
  "latitude" DECIMAL,
  "longitude" DECIMAL,
  "radius" DECIMAL,
  "deskripsi" VARCHAR(255),
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_geofence")
);

CREATE TABLE IF NOT EXISTS "status_armada" (
  "id_status_armada" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "status_armada" VARCHAR(255),
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_status_armada")
);

CREATE TABLE IF NOT EXISTS "jenis_armada" (
  "id_jenis_armada" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "jenis_armada" VARCHAR(255),
  "id_parent" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_jenis_armada")
);

CREATE TABLE IF NOT EXISTS "log_sensor" (
  "id_log_sensor" INTEGER,
  "id_perangkat" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  "time_stamp" TIMESTAMP,
  "data_sensor" JSON,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_log_sensor")
);

CREATE TABLE IF NOT EXISTS "log_perjalanan_armada" (
  "id_log_perjalanan_armada" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "id_perangkat" INTEGER,
  "id_armada" INTEGER,
  "id_delivery_order" INTEGER,
  "latitude" DECIMAL(10,7) NOT NULL,
  "longitude" DECIMAL(10,7) NOT NULL,
  "kecepatan_kmh" DECIMAL(5,2) NOT NULL,
  "kecepatan_sebelumnya_kmh" DECIMAL(5,2) NOT NULL,
  "percepatan_m_s2" DECIMAL(5,2) NOT NULL,
  "pengereman_mendadak" BOOLEAN,
  "akselerasi_kasar" BOOLEAN,
  "konsumsi_bahan_bakar_liter" DECIMAL(6,2),
  "penyimpangan_rute" BOOLEAN,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_log_perjalanan_armada")
);

CREATE TABLE IF NOT EXISTS "log_service" (
  "id_log_service" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "id_armada" INTEGER NOT NULL,
  "tanggal_service_terakhir" DATE,
  "interval_km" INTEGER,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_log_service")
);

CREATE TABLE IF NOT EXISTS "parent_armada" (
  "id_parent" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "kategori_jenis" VARCHAR(255),
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_parent")
);

CREATE TABLE IF NOT EXISTS "rute_perangkat" (
  "id_rute_perangkat" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  "id_rute" INTEGER NOT NULL,
  "id_perangkat" INTEGER NOT NULL,
  "waktu_berangkat" TIMESTAMP,
  "waktu_tiba" TIMESTAMP,
  "perubahan_rute" TEXT,
  "dibuat_pada" TIMESTAMP,
  "dibuat_oleh" INTEGER,
  "diubah_pada" TIMESTAMP,
  "diubah_oleh" INTEGER,
  PRIMARY KEY ("id_rute_perangkat")
);

CREATE INDEX IF NOT EXISTS "idx_log_gps_timestamp" ON "log_perangkat" ("timestamp");

COMMENT ON COLUMN "log_perangkat"."arah" IS '0-360= utara
';

COMMENT ON COLUMN "log_perangkat"."jarak" IS 'Kilometer';

ALTER TABLE "detail_salesorder" ADD FOREIGN KEY ("id_satuan") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "pembayaran_fee" ADD FOREIGN KEY ("id_rekening") REFERENCES "rekening_driver" ("id_rekening") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "order" ADD FOREIGN KEY ("id_order") REFERENCES "delivery_order" ("id_delivery_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "sales_order" ADD FOREIGN KEY ("id_sales_order") REFERENCES "order" ("id_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "po" ADD FOREIGN KEY ("id_po") REFERENCES "order" ("id_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "stok" ADD FOREIGN KEY ("id_lokasi") REFERENCES "lokasi_rak" ("id_lokasi") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "stok" ADD FOREIGN KEY ("id_produk") REFERENCES "produk" ("id_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "stok_movement" ADD FOREIGN KEY ("id_detail_sm") REFERENCES "detail_stockmovement" ("id_detail_sm") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_stockmovement" ADD FOREIGN KEY ("id_lokasi") REFERENCES "lokasi_rak" ("id_lokasi") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_po" ADD FOREIGN KEY ("id_produk") REFERENCES "produk" ("id_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_qc" ADD FOREIGN KEY ("id_lokasi") REFERENCES "lokasi_rak" ("id_lokasi") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "produk" ADD FOREIGN KEY ("id_kategori") REFERENCES "kategori_produk" ("id_kategori") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "produk" ADD FOREIGN KEY ("id_satuan") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "satuan" ADD FOREIGN KEY ("id_jenis") REFERENCES "jenis_satuan" ("id_jenis") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "konversi" ADD FOREIGN KEY ("id_produk") REFERENCES "produk" ("id_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "konversi" ADD FOREIGN KEY ("id_satuan") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "konversi" ADD FOREIGN KEY ("id_satuan_konversi") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "produk_gudang" ADD FOREIGN KEY ("id_gudang") REFERENCES "gudang" ("id_gudang") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "produk_gudang" ADD FOREIGN KEY ("id_produk") REFERENCES "produk" ("id_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "produk_gudang" ADD FOREIGN KEY ("id_mata_uang") REFERENCES "mata_uang" ("id_mata_uang") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "produk_gudang" ADD FOREIGN KEY ("id_satuan") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "atribut_produk" ADD FOREIGN KEY ("id_atribut") REFERENCES "atribut" ("id_atribut") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "atribut_produk" ADD FOREIGN KEY ("id_produk") REFERENCES "produk" ("id_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "atribut_produk" ADD FOREIGN KEY ("id_satuan") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_qc" ADD FOREIGN KEY ("id_qc") REFERENCES "quality_control" ("id_qc") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "quality_control" ADD FOREIGN KEY ("id_status_qc") REFERENCES "status_qc" ("id_status_qc") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "kriteria_produk" ADD FOREIGN KEY ("id_produk") REFERENCES "produk" ("id_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "kriteria_produk" ADD FOREIGN KEY ("id_satuan") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_qc" ADD FOREIGN KEY ("id_satuan") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_qc" ADD FOREIGN KEY ("id_detailpo") REFERENCES "detail_po" ("id_detailpo") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_qc" ADD FOREIGN KEY ("id_kriteria_produk") REFERENCES "kriteria_produk" ("id_kriteria_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "user_tenant" ADD FOREIGN KEY ("id_tenant") REFERENCES "tenant" ("id_tenant") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "pengembalian" ADD FOREIGN KEY ("id_satuan") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_pengembalian" ADD FOREIGN KEY ("id_attachment") REFERENCES "attachment" ("id_attachment") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_qc" ADD FOREIGN KEY ("id_detailqc") REFERENCES "detail_qc" ("id_detailqc") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_qc" ADD FOREIGN KEY ("id_attachment") REFERENCES "attachment" ("id_attachment") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_gudang" ADD FOREIGN KEY ("id_gudang") REFERENCES "gudang" ("id_gudang") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_gudang" ADD FOREIGN KEY ("id_attachment") REFERENCES "attachment" ("id_attachment") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "lokasi_rak" ADD FOREIGN KEY ("id_gudang") REFERENCES "gudang" ("id_gudang") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "produk" ADD FOREIGN KEY ("id_mata_uang") REFERENCES "mata_uang" ("id_mata_uang") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_stockmovement" ADD FOREIGN KEY ("id_satuan") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_stockmovement" ADD FOREIGN KEY ("id_produk") REFERENCES "produk" ("id_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_pengembalian" ADD FOREIGN KEY ("id_pengembalian") REFERENCES "pengembalian" ("id_pengembalian") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "quality_control" ADD FOREIGN KEY ("id_po") REFERENCES "po" ("id_po") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "po" ADD FOREIGN KEY ("id_tenant") REFERENCES "tenant" ("id_tenant") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "pengembalian" ADD FOREIGN KEY ("id_po") REFERENCES "po" ("id_po") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "pengembalian" ADD FOREIGN KEY ("id_produk") REFERENCES "produk" ("id_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "gudang" ADD FOREIGN KEY ("id_statusgudang") REFERENCES "status_gudang" ("id_statusgudang") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_po" ADD FOREIGN KEY ("id_po") REFERENCES "po" ("id_po") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment" ADD FOREIGN KEY ("id_jenis_file") REFERENCES "jenis_file" ("id_jenis_file") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "jenis_file" ADD FOREIGN KEY ("id_jenis_transaksi") REFERENCES "jenis_transaksi" ("id_jenis_transaksi") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_po" ADD FOREIGN KEY ("id_satuan") REFERENCES "satuan" ("id_satuan") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_driver" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "notifikasi" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "laporan_darurat" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "pembayaran_fee" ADD FOREIGN KEY ("id_delivery_order") REFERENCES "delivery_order" ("id_delivery_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "rekening_driver" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "driver_armada" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "deliveryorder_salesorder" ADD FOREIGN KEY ("id_delivery_order") REFERENCES "delivery_order" ("id_delivery_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "deliveryorder_salesorder" ADD FOREIGN KEY ("id_sales_order") REFERENCES "sales_order" ("id_sales_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "rekening_driver" ADD FOREIGN KEY ("id_bank") REFERENCES "bank" ("id_bank") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "chat_attachment" ADD FOREIGN KEY ("id_chat") REFERENCES "log_chat" ("id_chat") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "daftar_user" ADD FOREIGN KEY ("id_status") REFERENCES "status_driver" ("id_status") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "rating" ADD FOREIGN KEY ("id_delivery_order") REFERENCES "delivery_order" ("id_delivery_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "notifikasi" ADD FOREIGN KEY ("id_jenis_notifikasi") REFERENCES "jenis_notifikasi" ("id_jenis_notifikasi") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "laporan_darurat" ADD FOREIGN KEY ("id_jenis_insiden") REFERENCES "jenis_insiden" ("id_jenis_insiden") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "delivery_order" ADD FOREIGN KEY ("id_armada") REFERENCES "armada_tms" ("id_armada") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "driver_armada" ADD FOREIGN KEY ("id_armada") REFERENCES "armada_tms" ("id_armada") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "pembayaran_fee" ADD FOREIGN KEY ("id_metode_pembayaran") REFERENCES "metode_pembayaran" ("id_metode_pembayaran") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_salesorder" ADD FOREIGN KEY ("id_sales_order") REFERENCES "sales_order" ("id_sales_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_deliveryorder" ADD FOREIGN KEY ("id_delivery_order") REFERENCES "delivery_order" ("id_delivery_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "perangkat_gps_driver" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_aktifitas_driver" ADD FOREIGN KEY ("id_gps_driver") REFERENCES "perangkat_gps_driver" ("id_gps_driver") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_panggilan" ADD FOREIGN KEY ("id_pengirim") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_panggilan" ADD FOREIGN KEY ("id_penerima") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_chat" ADD FOREIGN KEY ("id_pengirim") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_chat" ADD FOREIGN KEY ("id_penerima") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "chat_attachment" ADD FOREIGN KEY ("id_attachment") REFERENCES "attachment" ("id_attachment") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_driver" ADD FOREIGN KEY ("id_attachment") REFERENCES "attachment" ("id_attachment") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "order" ADD FOREIGN KEY ("id_order") REFERENCES "jenis_order" ("id_jenis_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "daftar_user" ADD FOREIGN KEY ("id_kontakdarurat") REFERENCES "kontak_darurat" ("id_kontakdarurat") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "user_tenant" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "quality_control" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "stok_movement" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "user_role" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "user_role" ADD FOREIGN KEY ("id_role") REFERENCES "role" ("id_role") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "armada_tms" ADD FOREIGN KEY ("id_status_armada") REFERENCES "status_armada" ("id_status_armada") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "armada_tms" ADD FOREIGN KEY ("id_jenis_armada") REFERENCES "jenis_armada" ("id_jenis_armada") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_perjalanan_armada" ADD FOREIGN KEY ("id_armada") REFERENCES "armada_tms" ("id_armada") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "armada_perangkat" ADD FOREIGN KEY ("id_perangkat") REFERENCES "perangkat" ("id_perangkat") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "armada_perangkat" ADD FOREIGN KEY ("id_armada") REFERENCES "armada_tms" ("id_armada") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "pengingat_pemeliharaan_armada" ADD FOREIGN KEY ("id_armada") REFERENCES "armada_tms" ("id_armada") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_perangkat" ADD FOREIGN KEY ("id_perangkat") REFERENCES "perangkat" ("id_perangkat") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_perangkat" ADD FOREIGN KEY ("id_attachment") REFERENCES "attachment" ("id_attachment") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_perangkat" ADD FOREIGN KEY ("id_perangkat") REFERENCES "perangkat" ("id_perangkat") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_perjalanan_armada" ADD FOREIGN KEY ("id_perangkat") REFERENCES "perangkat" ("id_perangkat") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "pengingat_pemeliharaan_armada" ADD FOREIGN KEY ("id_log_service") REFERENCES "log_service" ("id_log_service") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_service" ADD FOREIGN KEY ("id_armada") REFERENCES "armada_tms" ("id_armada") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "rute_perangkat" ADD FOREIGN KEY ("id_rute") REFERENCES "rute" ("id_rute") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "rute_perangkat" ADD FOREIGN KEY ("id_perangkat") REFERENCES "perangkat" ("id_perangkat") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "alert_geofence" ADD FOREIGN KEY ("id_geofence") REFERENCES "geofence" ("id_geofence") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "rute" ADD FOREIGN KEY ("id_geofence") REFERENCES "geofence" ("id_geofence") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "alert_geofence" ADD FOREIGN KEY ("id_geofence") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_sensor" ADD FOREIGN KEY ("id_perangkat") REFERENCES "perangkat" ("id_perangkat") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "jenis_armada" ADD FOREIGN KEY ("id_parent") REFERENCES "parent_armada" ("id_parent") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "laporan_pengemudi" ADD FOREIGN KEY ("id_log_perjalanan_armada") REFERENCES "log_perjalanan_armada" ("id_log_perjalanan_armada") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_armada" ADD FOREIGN KEY ("id_attachment") REFERENCES "attachment" ("id_attachment") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "attachment_armada" ADD FOREIGN KEY ("id_armada") REFERENCES "armada_tms" ("id_armada") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "alert_geofence" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_salesorder" ADD FOREIGN KEY ("id_produk") REFERENCES "produk" ("id_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "log_chat" ADD FOREIGN KEY ("id_order") REFERENCES "order" ("id_order") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "laporan_pengemudi" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "delivery_order" ADD FOREIGN KEY ("id_user") REFERENCES "daftar_user" ("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "detail_deliveryorder" ADD FOREIGN KEY ("id_produk") REFERENCES "produk" ("id_produk") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "produk" ADD FOREIGN KEY ("id_tenant") REFERENCES "tenant" ("id_tenant") ON DELETE NO ACTION ON UPDATE NO ACTION;
